
load("@rules_cc//cc:objc_library.bzl", "objc_library")

objc_library(
    name = "UIKitRuntimeUtils",
    enable_modules = True,
    module_name = "UIKitRuntimeUtils",
    srcs = glob([
        "Source/UIKitRuntimeUtils/*.m",
    ]),
    copts = [
        "-Wno-error=deprecated-declarations",
    ],
    hdrs = glob([
        "Source/UIKitRuntimeUtils/*.h",
    ]),
    includes = [
      "Source",
    ],
    deps = [
      "//submodules/AsyncDisplayKit",
      "//submodules/ObjCRuntimeUtils",
    ],
    sdk_frameworks = [
      "Foundation",
      "UIKit",
      "WebKit",
    ],
    visibility = [
        "//visibility:public",
    ],
)
