load("@rules_cc//cc:objc_library.bzl", "objc_library")

objc_library(
    name = "BuildConfigExtra",
    enable_modules = True,
    module_name = "BuildConfigExtra",
    srcs = glob([
        "Sources/**/*.m",
        "Sources/**/*.h",
    ], allow_empty=True),
    copts = [
        "-Werror",
        "-Wno-error=deprecated-declarations",
    ],
    hdrs = glob([
        "PublicHeaders/**/*.h",
    ]),
    includes = [
        "PublicHeaders",
    ],
    deps = [
        "//submodules/PKCS:PKCS",
    ],
    sdk_frameworks = [
        "Foundation",
    ],
    visibility = [
        "//visibility:public",
    ],
)
